# Generated by Django 3.0.6 on 2020-05-25 09:19

# Django
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, db_index=True)),
                ('scheduled', models.DateTimeField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.EventType')),
            ],
        ),
    ]
